language: objective-c
osx_image: xcode7
before_install:
  - cd Example
install:
  - sudo gem install xcpretty
script:
  - pod install
  - xcodebuild -workspace GDataXML-HTML.xcworkspace -scheme GDataXML-HTML -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6' test | xcpretty -c && exit ${PIPESTATUS[0]}
